version: '3'
services:
  db:
    container_name: tableberg_dev_serve_db
    image: mariadb:latest
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: "dotcamp"
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 5s
      retries: 10

  wordpress:
    container_name: tableberg_dev_serve
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db: 
        condition: service_healthy
    ports:
      - "8000:80"
    volumes:
      - ../../packages/tableberg:/var/www/html/wp-content/plugins/tableberg
      - ../../packages/pro:/var/www/html/wp-content/plugins/tableberg-pro
volumes:
  db_data: